# Employee and FulltimeEmployee Classes


In [8]:
class Employee:
    employee_count = 0  # Class variable to count the number of Employees

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_count += 1

    @staticmethod
    def average_salary(employees):
        if not employees:
            return 0
        total_salary = sum(emp.salary for emp in employees)
        return total_salary / len(employees)

class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        super().__init__(name, family, salary, department)

# Creating instances and calling member functions
emp1 = Employee("Bharathwaj", "Manasa", 50000, "HR")
emp2 = Employee("Sudeep", "Riya", 60000, "IT")
ft_emp1 = FulltimeEmployee("Vineel", "Teju", 70000, "Finance")

print(f"Total number of employees: {Employee.employee_count}")
print(f"Average salary: ${Employee.average_salary([emp1, emp2, ft_emp1]):.2f}")

Total number of employees: 3
Average salary: $60000.00


# NumPy Vector Operations

In [9]:
import numpy as np

# Create random vector of size 20 with floats in range 1-20
vector = np.random.uniform(1, 20, 20)

print("Original vector:")
print(vector)

# Reshape the array to 4 by 5
matrix = vector.reshape(4, 5)

print("\nReshaped 4x5 matrix:")
print(matrix)

# Replace the max in each row by 0
matrix[np.arange(4), np.argmax(matrix, axis=1)] = 0

print("\nMatrix after replacing max in each row with 0:")
print(matrix)

Original vector:
[17.67237352  7.42665896  8.3375746   7.52809594  7.70231683  1.12851293
 12.90837856 12.69242333 15.77947933 14.99937083  6.61148935 12.74996452
  6.60409526 17.06573567 15.18076377  2.54217579 13.02427644 19.87313968
 10.11508953 10.78694679]

Reshaped 4x5 matrix:
[[17.67237352  7.42665896  8.3375746   7.52809594  7.70231683]
 [ 1.12851293 12.90837856 12.69242333 15.77947933 14.99937083]
 [ 6.61148935 12.74996452  6.60409526 17.06573567 15.18076377]
 [ 2.54217579 13.02427644 19.87313968 10.11508953 10.78694679]]

Matrix after replacing max in each row with 0:
[[ 0.          7.42665896  8.3375746   7.52809594  7.70231683]
 [ 1.12851293 12.90837856 12.69242333  0.         14.99937083]
 [ 6.61148935 12.74996452  6.60409526  0.         15.18076377]
 [ 2.54217579 13.02427644  0.         10.11508953 10.78694679]]
